spring.application.name=dockerHomework
management.endpoints.web.base-path=
management.endpoints.web.path-mapping.health=/health
server.port=8000
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${DB-HOST:jdbc:postgresql://localhost:5432/otus_db}
spring.datasource.username=${DB-USERNAME:postgres}
spring.datasource.password=${DB-PASSWORD:121}

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.enabled=true