apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      label-test: app-pod
  template:
    metadata:
      labels:
        label-test: app-pod
    spec:
      containers:
        - name: app
          image: mirgraf/mirgraf_rep:V5
          ports:
            - containerPort: 8000
          env:
            - name: DB-HOST
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: DB-HOST
            - name: DB-USERNAME
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: DB-USERNAME
            - name: DB-PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: DB-PASSWORD
