apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      label: app-pod
  template:
    metadata:
      labels:
        label: app-pod
    spec:
      containers:
        - name: app
          image: mirgraf/mirgraf_rep:v2