apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: service-monitor
spec:
  endpoints:
    - port: nginx-exporter
      scrapeTimeout: 30s
      path: /stub_status
      honorLabels: true
      scheme: http
    - port: metrics123
      scrapeTimeout: 30s
      path: /actuator/prometheus
      honorLabels: true
      scheme: http
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      label-test: service-test
      app: nginx-exporter

